[project]
name = "lvn"
dynamic = ["version"]
requires-python = ">=3.10"
readme = "README.md"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
train = "lvn.scripts.train:main"

[tool.setuptools.packages.find]
include = ["lvn"]